spring :
  application :
           name : hello-client
server :
   port : 8071
   
eureka :
   client :
     register-with-eureka : true
     fetch-registry : true
     serviceUrl :
        defaultZone : http://localhost:8070/eureka/
   instance:
     hostname: localhost     