spring:
  application:
           name: hello-client
server:
   port: 8071
   
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
        defaultZone: http://localhost:8070/eureka/
   instance:
     hostname: localhost
     
hystrix: 
   command:
     default:
      execution:
         timeout:
           enabled: true
         isolation:
           semaphore:
              maxConcurrentRequests: 10
           thread:
              timeoutInMilliseconds: 10
 #   maxConcurrentRequests - default - 10             
 #   timeoutInMilliseconds - default 1000 ms  
 #   requestVolumeThreshold - default -20   
   circuitBreaker: 
     requestVolumeThreshold: 30 
   threadpool:
     HystrixThreadpoolKey:
       coreSize: 64
     default:
       coreSize: 64                
            
           